package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ErrorResponse Represents an error.
// swagger:model ErrorResponse
const (
	StatusCommandErr = -1

)
type ErrorResponse struct {
	// The error message.
	// Required: true
	Message string `json:"message"`
	ErrorID  int   `json:"id"`
}
